apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-appset
  namespace: mirko-account-qa-free-ha
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/mteodor/argocd-example-apps
      revision: HEAD
      directories:
      - path: helm-appset/templates/*
  template:
    metadata:
      name: '{{.path.basename}}'
      labels:
        harness.io/envRef: Prod
        harness.io/serviceRef: helmappset
    spec:
      project: "5b02f9dc"
      source:
        chart: grafana
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: 7.0.8
        helm:
          values: >-
              replicas: 1              
              autoscaling:
                enabled: false
                minReplicas: 1
                maxReplicas: 5
                targetCPU: "60"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
