apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appofapps
spec:
  generators:
    - list:
        elements:
          - cluster: engineering-dev
            url: 'https://35.233.139.33'
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: 'appofapps'
    spec:
      project: ad5599b7
      source:
        repoURL: https://github.com/mteodor/argocd-example-apps.git
        targetRevision: mirko-namespaced
        path: guestbook
      syncPolicy:
        syncOptions:
         - Validate=true     
         - CreateNamespace=true
      destination:
        server: '{{url}}'
        namespace: mirko-namespaced
