apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: engineering-dev
            url: https://kubernetes.default.svc
            env: dev
            namespace: cbp-dev-ns
            team: frontend
          - cluster: engineering-dev1
            url: https://kubernetes.default.svc
            namespace: cbp-prod-ds
            env: prod
            team: backend
  template:
    metadata:
      name: '{{cluster}}-guestbook'
      labels:
        harness.io/env-type: '{{env}}'
        harness.io/team: '{{team}}'
    spec:
      project: f6bd2309
      source:
        repoURL: https://github.com/mteodor/argocd-example-apps.git
        targetRevision: cbp-test
        path: guestbook/{{cluster}}
      syncPolicy:
        syncOptions:
         - Validate=true     
         - CreateNamespace=true
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
