apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: engineering-test
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: f6bd2309
      source:
        repoURL: https://github.com/mteodor/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook/{{cluster}}
      syncPolicy:
        syncOptions:
         - Validate=true     
         - CreateNamespace=true
      destination:
        server: '{{url}}'
        namespace: mirko-test4
