apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appofapps
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: 'appofapps'
    spec:
      project: 14a3dc9e
      source:
        repoURL: https://github.com/mteodor/argocd-example-apps.git
        targetRevision: HEAD
        path: apps
      syncPolicy:
        syncOptions:
         - Validate=true     
         - CreateNamespace=true
      destination:
        server: '{{url}}'
        namespace: mirko-namespaced
