metadata:
  name: "test2"
  labels:
    harness.io/serviceRef: "helmapp"
    harness.io/envRef: "prod1"
redisPort: "6378"
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "redis-test2"
  project: "3ca2a422"
  source:
    repoURL: "https://charts.helm.sh/stable/"
    targetRevision: "10.5.1"
    chart: "redis"
    helm:
      passCredentials: true
