apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - list:
        elements:
          - cluster: cluster2
            url: https://kubernetes.default.svc
          - cluster: cluster3
            url: https://kubernetes.default.svc
          - cluster: cluster4
            url: https://kubernetes.default.svc
          - cluster: cluster5
            url: https://kubernetes.default.svc
          - cluster: cluster6
            url: https://kubernetes.default.svc
          - cluster: cluster7
            url: https://kubernetes.default.svc
          - cluster: cluster8
            url: https://kubernetes.default.svc
          - cluster: cluster9
            url: https://kubernetes.default.svc
          - cluster: cluster10
            url: https://kubernetes.default.svc
          - cluster: cluster11
            url: https://kubernetes.default.svc
          - cluster: cluster12
            url: https://kubernetes.default.svc
          - cluster: cluster13
            url: https://kubernetes.default.svc
          - cluster: cluster14
            url: https://kubernetes.default.svc
          - cluster: cluster15
            url: https://kubernetes.default.svc
          - cluster: cluster16
            url: https://kubernetes.default.svc
          - cluster: cluster17
            url: https://kubernetes.default.svc
          - cluster: cluster18
            url: https://kubernetes.default.svc
          - cluster: cluster19
            url: https://kubernetes.default.svc
          - cluster: cluster20
            url: https://kubernetes.default.svc
          - cluster: cluster21
            url: https://kubernetes.default.svc
          - cluster: cluster22
            url: https://kubernetes.default.svc
          - cluster: cluster23
            url: https://kubernetes.default.svc
          - cluster: cluster24
            url: https://kubernetes.default.svc
          - cluster: cluster25
            url: https://kubernetes.default.svc
          - cluster: cluster26
            url: https://kubernetes.default.svc
          - cluster: cluster27
            url: https://kubernetes.default.svc
          - cluster: cluster28
            url: https://kubernetes.default.svc
          - cluster: cluster29
            url: https://kubernetes.default.svc
          - cluster: cluster30
            url: https://kubernetes.default.svc
          - cluster: cluster31
            url: https://kubernetes.default.svc
          - cluster: cluster32
            url: https://kubernetes.default.svc
          - cluster: cluster33
            url: https://kubernetes.default.svc
          - cluster: cluster34
            url: https://kubernetes.default.svc
          - cluster: cluster35
            url: https://kubernetes.default.svc
          - cluster: cluster36
            url: https://kubernetes.default.svc
          - cluster: cluster37
            url: https://kubernetes.default.svc
          - cluster: cluster38
            url: https://kubernetes.default.svc
          - cluster: cluster39
            url: https://kubernetes.default.svc
          - cluster: cluster40
            url: https://kubernetes.default.svc
          - cluster: muster1
            url: https://kubernetes.default.svc
          - cluster: muster2
            url: https://kubernetes.default.svc
          - cluster: muster3
            url: https://kubernetes.default.svc
          - cluster: muster4
            url: https://kubernetes.default.svc
          - cluster: muster5
            url: https://kubernetes.default.svc
          - cluster: muster6
            url: https://kubernetes.default.svc
          - cluster: muster7
            url: https://kubernetes.default.svc
          - cluster: muster8
            url: https://kubernetes.default.svc
          - cluster: muster9
            url: https://kubernetes.default.svc
          - cluster: muster10
            url: https://kubernetes.default.svc
          - cluster: muster11
            url: https://kubernetes.default.svc
          - cluster: muster12
            url: https://kubernetes.default.svc
          - cluster: muster13
            url: https://kubernetes.default.svc
          - cluster: muster14
            url: https://kubernetes.default.svc
          - cluster: muster15
            url: https://kubernetes.default.svc
          - cluster: muster16
            url: https://kubernetes.default.svc
          - cluster: muster17
            url: https://kubernetes.default.svc
          - cluster: muster18
            url: https://kubernetes.default.svc
          - cluster: muster19
            url: https://kubernetes.default.svc
          - cluster: muster20
            url: https://kubernetes.default.svc
          - cluster: sluster1
            url: https://kubernetes.default.svc
          - cluster: sluster2
            url: https://kubernetes.default.svc
          - cluster: sluster3
            url: https://kubernetes.default.svc
          - cluster: sluster4
            url: https://kubernetes.default.svc
          - cluster: sluster5
            url: https://kubernetes.default.svc
          - cluster: sluster6
            url: https://kubernetes.default.svc
          - cluster: sluster7
            url: https://kubernetes.default.svc
          - cluster: sluster8
            url: https://kubernetes.default.svc
          - cluster: sluster9
            url: https://kubernetes.default.svc
          - cluster: sluster10
            url: https://kubernetes.default.svc
          - cluster: sluster11
            url: https://kubernetes.default.svc
          - cluster: sluster12
            url: https://kubernetes.default.svc
          - cluster: sluster13
            url: https://kubernetes.default.svc
          - cluster: sluster14
            url: https://kubernetes.default.svc
          - cluster: sluster15
            url: https://kubernetes.default.svc
          - cluster: sluster16
            url: https://kubernetes.default.svc
          - cluster: sluster17
            url: https://kubernetes.default.svc
          - cluster: sluster18
            url: https://kubernetes.default.svc
          - cluster: sluster19
            url: https://kubernetes.default.svc
          - cluster: sluster20
            url: https://kubernetes.default.svc
          - cluster: sluster21
            url: https://kubernetes.default.svc
          - cluster: sluster22
            url: https://kubernetes.default.svc
          - cluster: sluster23
            url: https://kubernetes.default.svc
          - cluster: sluster24
            url: https://kubernetes.default.svc
          - cluster: sluster25
            url: https://kubernetes.default.svc
          - cluster: sluster26
            url: https://kubernetes.default.svc
          - cluster: sluster27
            url: https://kubernetes.default.svc
          - cluster: sluster28
            url: https://kubernetes.default.svc
          - cluster: sluster29
            url: https://kubernetes.default.svc
          - cluster: sluster30
            url: https://kubernetes.default.svc
          - cluster: sluster31
            url: https://kubernetes.default.svc
          - cluster: sluster32
            url: https://kubernetes.default.svc
          - cluster: sluster33
            url: https://kubernetes.default.svc
          - cluster: sluster34
            url: https://kubernetes.default.svc
          - cluster: sluster35
            url: https://kubernetes.default.svc
          - cluster: sluster36
            url: https://kubernetes.default.svc
          - cluster: sluster37
            url: https://kubernetes.default.svc
          - cluster: sluster38
            url: https://kubernetes.default.svc
          - cluster: sluster39
            url: https://kubernetes.default.svc
          - cluster: sluster40
            url: https://kubernetes.default.svc
          - cluster: mluster1
            url: https://kubernetes.default.svc
          - cluster: mluster2
            url: https://kubernetes.default.svc
          - cluster: mluster3
            url: https://kubernetes.default.svc
          - cluster: mluster4
            url: https://kubernetes.default.svc
          - cluster: mluster5
            url: https://kubernetes.default.svc
          - cluster: mluster6
            url: https://kubernetes.default.svc
          - cluster: mluster7
            url: https://kubernetes.default.svc
          - cluster: mluster8
            url: https://kubernetes.default.svc
          - cluster: mluster9
            url: https://kubernetes.default.svc
          - cluster: mluster10
            url: https://kubernetes.default.svc
          - cluster: mluster11
            url: https://kubernetes.default.svc
          - cluster: mluster12
            url: https://kubernetes.default.svc
          - cluster: mluster13
            url: https://kubernetes.default.svc
          - cluster: mluster14
            url: https://kubernetes.default.svc
          - cluster: mluster15
            url: https://kubernetes.default.svc
          - cluster: mluster16
            url: https://kubernetes.default.svc
          - cluster: mluster17
            url: https://kubernetes.default.svc
          - cluster: mluster18
            url: https://kubernetes.default.svc
          - cluster: mluster19
            url: https://kubernetes.default.svc
          - cluster: mluster20
            url: https://kubernetes.default.svc
          - cluster: mankrit1
            url: https://kubernetes.default.svc
          - cluster: mankrit2
            url: https://kubernetes.default.svc
          - cluster: mankrit3
            url: https://kubernetes.default.svc
          - cluster: mankrit4
            url: https://kubernetes.default.svc
          - cluster: mankrit5
            url: https://kubernetes.default.svc
          - cluster: mankrit6
            url: https://kubernetes.default.svc
          - cluster: mankrit7
            url: https://kubernetes.default.svc
          - cluster: mankrit8
            url: https://kubernetes.default.svc
          - cluster: mankrit9
            url: https://kubernetes.default.svc
          - cluster: mankrit10
            url: https://kubernetes.default.svc
          - cluster: mankrit11
            url: https://kubernetes.default.svc
          - cluster: mankrit12
            url: https://kubernetes.default.svc
          - cluster: mankrit13
            url: https://kubernetes.default.svc
          - cluster: mankrit14
            url: https://kubernetes.default.svc
          - cluster: mankrit15
            url: https://kubernetes.default.svc
          - cluster: mankrit16
            url: https://kubernetes.default.svc
          - cluster: mankrit17
            url: https://kubernetes.default.svc
          - cluster: mankrit18
            url: https://kubernetes.default.svc
          - cluster: mankrit19
            url: https://kubernetes.default.svc
          - cluster: mankrit20
            url: https://kubernetes.default.svc
          - cluster: mankrit21
            url: https://kubernetes.default.svc
          - cluster: mankrit22
            url: https://kubernetes.default.svc
          - cluster: mankrit23
            url: https://kubernetes.default.svc
          - cluster: mankrit24
            url: https://kubernetes.default.svc
          - cluster: mankrit25
            url: https://kubernetes.default.svc
          - cluster: mankrit26
            url: https://kubernetes.default.svc
          - cluster: mankrit27
            url: https://kubernetes.default.svc
          - cluster: mankrit28
            url: https://kubernetes.default.svc
          - cluster: mankrit29
            url: https://kubernetes.default.svc
          - cluster: mankrit30
            url: https://kubernetes.default.svc
          - cluster: mankrit31
            url: https://kubernetes.default.svc
          - cluster: mankrit32
            url: https://kubernetes.default.svc
          - cluster: mankrit33
            url: https://kubernetes.default.svc
          - cluster: mankrit34
            url: https://kubernetes.default.svc
          - cluster: mankrit35
            url: https://kubernetes.default.svc
          - cluster: mankrit36
            url: https://kubernetes.default.svc
          - cluster: mankrit37
            url: https://kubernetes.default.svc
          - cluster: mankrit38
            url: https://kubernetes.default.svc
          - cluster: mankrit39
            url: https://kubernetes.default.svc
          - cluster: mankrit40
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: 8df94870
      source:
        repoURL: https://github.com/mteodor/argocd-example-apps.git
        targetRevision: fake-guestbook
        path: guestbook-list/guestbook
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}-guestbook'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true
        - Prune=true
        - PruneLast=true
