{{- range .Values.applications }}
{{- $config := $.Values.config -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ printf "example.%s" .name | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://34.83.50.192
      - cluster: engineering-prod
        url: https://35.233.139.33
      # - cluster: finance-preprod
      #   url: https://9.8.7.6
  template:
    metadata:
      name: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example.%s" .name }}'
    spec:
      project: {{ $config.project }}
      source:
        repoURL: https://github.com/mteodor/argocd-example-apps
        targetRevision: nginx-monitoring
        path: nginx
      destination:
        namespace: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example.%s" .name }}'
        server: '{{ "{{" }}.url{{ "}}" }}'
---
{{ end -}}
