{{- range .Values.applications }}
{{- $config := $.Values.config -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ printf "example.%s" .name | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
        - list:
            elements:
              - cluster: eng-dev1
              - cluster: eng-dev2
              - cluster: eng-dev3
              - cluster: eng-dev4
              - cluster: eng-dev5
              - cluster: eng-dev6
              - cluster: eng-dev7
              - cluster: eng-dev8
              - cluster: eng-dev9
              - cluster: eng-dev10
              - cluster: eng-dev11
              - cluster: eng-dev12
              - cluster: eng-dev13
              - cluster: eng-dev14
              - cluster: eng-dev15
              - cluster: eng-dev16
              - cluster: eng-dev17
              - cluster: eng-dev18
              - cluster: eng-dev19
              - cluster: eng-dev20
              - cluster: eng-dev21
              - cluster: eng-dev22
              - cluster: eng-dev23
              - cluster: eng-dev24
              - cluster: eng-dev25
              - cluster: eng-dev26
              - cluster: eng-dev27
              - cluster: eng-dev28
              - cluster: eng-dev29
              - cluster: eng-dev30
              - cluster: eng-dev31
              - cluster: eng-dev32
              - cluster: eng-dev33
              - cluster: eng-dev34
              - cluster: eng-dev35
              - cluster: eng-dev36
              - cluster: eng-dev37
              - cluster: eng-dev38
              - cluster: eng-dev39
              - cluster: ceng-dev40
              - cluster: eng-dev41
              - cluster: eng-dev42
              - cluster: eng-dev43
              - cluster: eng-dev44
              - cluster: eng-dev45
              - cluster: eng-dev46
              - cluster: eng-dev47
              - cluster: eng-dev48
              - cluster: eng-dev49
              - cluster: eng-dev50

  template:
    metadata:
      name: '{{ "{{" }}.nameNormalized{{ "}}" }}-{{ "{{" }}.cluster{{ "}}" }}-{{ printf "ccc-%s" .name }}'
    spec:
      project: {{ $config.project }}
      source:
        repoURL: {{ $config.repoURL }}
        targetRevision: {{ $config.targetRevision }}
        path: {{ $config.path }}
        helm:
          values: |
            someValue: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example-%s" .name }}'
            name: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example-%s" .name }}'
            namespace: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example-%s" .name }}'
      destination:
        namespace: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example-%s" .name }}'
        server: '{{ "{{" }}.server{{ "}}" }}'
      syncPolicy:
        syncOptions:
        - Replace=true
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
---
{{ end -}}
