{{- range .Values.applications }}
{{- $config := $.Values.config -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ printf "example.%s" .name | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
        - list:
            elements:
              - cluster: engineering-dev1
              - cluster: engineering-dev2
              - cluster: engineering-dev3
              - cluster: engineering-dev4
              - cluster: engineering-dev5
              - cluster: engineering-dev6
              - cluster: engineering-dev7
              - cluster: engineering-dev8
              - cluster: engineering-dev9
              - cluster: engineering-dev10
              - cluster: engineering-dev11
              - cluster: engineering-dev12
              - cluster: engineering-dev13
              - cluster: engineering-dev14
              - cluster: engineering-dev15
              - cluster: engineering-dev16
              - cluster: engineering-dev17
              - cluster: engineering-dev18
              - cluster: engineering-dev19
              - cluster: engineering-dev20
              - cluster: engineering-dev21
              - cluster: engineering-dev22
              - cluster: engineering-dev23
              - cluster: engineering-dev24
              - cluster: engineering-dev25
              - cluster: engineering-dev26
              - cluster: engineering-dev27
              - cluster: engineering-dev28
              - cluster: engineering-dev29
              - cluster: engineering-dev30
              - cluster: engineering-dev31
              - cluster: engineering-dev32
              - cluster: engineering-dev33
              - cluster: engineering-dev34
              - cluster: engineering-dev35
              - cluster: engineering-dev36
              - cluster: engineering-dev37
              - cluster: engineering-dev38
              - cluster: engineering-dev39
              - cluster: engineering-dev40
              - cluster: engineering-dev41
              - cluster: engineering-dev42
              - cluster: engineering-dev43
              - cluster: engineering-dev44
              - cluster: engineering-dev45
              - cluster: engineering-dev46
              - cluster: engineering-dev47
              - cluster: engineering-dev48
              - cluster: engineering-dev49
              - cluster: engineering-dev50
              - cluster: engineering-dev51
              - cluster: engineering-dev52
              - cluster: engineering-dev53
              - cluster: engineering-dev54
              - cluster: engineering-dev55
              - cluster: engineering-dev56
              - cluster: engineering-dev57
              - cluster: engineering-dev58
              - cluster: engineering-dev59
              - cluster: engineering-dev60
              - cluster: engineering-dev61
              - cluster: engineering-dev62
              - cluster: engineering-dev63
              - cluster: engineering-dev64
              - cluster: engineering-dev65
              - cluster: engineering-dev66
              - cluster: engineering-dev67
              - cluster: engineering-dev68
              - cluster: engineering-dev69
              - cluster: engineering-dev70
              - cluster: engineering-dev71
              - cluster: engineering-dev72
              - cluster: engineering-dev73
              - cluster: engineering-dev74
              - cluster: engineering-dev75
              - cluster: engineering-dev76
              - cluster: engineering-dev77
              - cluster: engineering-dev78
              - cluster: engineering-dev79
              - cluster: engineering-dev80
              - cluster: engineering-dev81
              - cluster: engineering-dev82
              - cluster: engineering-dev83
              - cluster: engineering-dev84
              - cluster: engineering-dev85
              - cluster: engineering-dev86
              - cluster: engineering-dev87
              - cluster: engineering-dev88
              - cluster: engineering-dev89
              - cluster: engineering-dev90
              - cluster: engineering-dev91
              - cluster: engineering-dev92
              - cluster: engineering-dev93
              - cluster: engineering-dev94
              - cluster: engineering-dev95
              - cluster: engineering-dev96
              - cluster: engineering-dev97
              - cluster: engineering-dev98
              - cluster: engineering-dev99
              - cluster: engineering-dev100
    
              
          # - cluster: finance-preprod
          #   url: https://9.8.7.6
  template:
    metadata:
      name: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example.%s" .name }}'
    spec:
      project: {{ $config.project }}
      source:
        repoURL: {{ $config.repoURL }}
        targetRevision: {{ $config.targetRevision }}
        path: {{ $config.path }}
        helm:
          values: |
            someValue: {{ .cluster }}
            name: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example-%s" .name }}'
            namespace: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example-%s" .name }}'
      destination:
        namespace: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example-%s" .name }}'
        server: '{{ "{{" }}.server{{ "}}" }}'
      syncPolicy:
        syncOptions:
        - Replace=true
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
---
{{ end -}}
