{{- range .Values.applications }}
{{- $config := $.Values.config -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ printf "example.%s" .name | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
        - list:
            elements:
              - cluster: eng-dev1
                server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{ "{{" }}.nameNormalized{{ "}}" }}-{{ "{{" }}.cluster{{ "}}" }}-{{ printf "ccc-%s" .name }}'
    spec:
      project: {{ $config.project }}
      source:
        repoURL: {{ $config.repoURL }}
        targetRevision: {{ $config.targetRevision }}
        path: {{ $config.path }}
        helm:
          values: |
            someValue: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example-%s" .name }}'
            name: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example-%s" .name }}'
            namespace: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example-%s" .name }}'
      destination:
        namespace: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example-%s" .name }}'
        server: '{{ "{{" }}.server{{ "}}" }}'
      syncPolicy:
        syncOptions:
        - Replace=true
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
---
{{ end -}}
