{{- range .Values.applications }}
{{- $config := $.Values.config -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ printf "example.%s" .name | quote }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
        - list:
            elements:
              - cluster: eng-dev1
              - cluster: eng-dev2
              - cluster: eng-dev3
              - cluster: eng-dev4
              - cluster: eng-dev5
              - cluster: eng-dev6
              - cluster: eng-dev7
              - cluster: eng-dev8
              - cluster: eng-dev9
              - cluster: eng-dev10
              - cluster: eng-dev11
              - cluster: eng-dev12
              - cluster: eng-dev13
              - cluster: eng-dev14
              - cluster: eng-dev15
              - cluster: eng-dev16
              - cluster: eng-dev17
              - cluster: eng-dev18
              - cluster: eng-dev19
              - cluster: eng-dev20
              - cluster: eng-dev21
              - cluster: eng-dev22
              - cluster: eng-dev23
              - cluster: eng-dev24
              - cluster: eng-dev25
              - cluster: eng-dev26
              - cluster: eng-dev27
              - cluster: eng-dev28
              - cluster: eng-dev29
              - cluster: eng-dev30
              - cluster: eng-dev31
              - cluster: eng-dev32
              - cluster: eng-dev33
              - cluster: eng-dev34
              - cluster: eng-dev35
              - cluster: eng-dev36
              - cluster: eng-dev37
              - cluster: eng-dev38
              - cluster: eng-dev39
              - cluster: eng-dev40
              - cluster: eng-dev41
              - cluster: eng-dev42
              - cluster: eng-dev43
              - cluster: eng-dev44
              - cluster: eng-dev45
              - cluster: eng-dev46
              - cluster: eng-dev47
              - cluster: eng-dev48
              - cluster: eng-dev49
              - cluster: eng-dev50
              - cluster: eng-dev51
              - cluster: eng-dev52
              - cluster: eng-dev53
              - cluster: eng-dev54
              - cluster: eng-dev55
              - cluster: eng-dev56
              - cluster: eng-dev57
              - cluster: eng-dev58
              - cluster: eng-dev59
              - cluster: eng-dev60
              - cluster: eng-dev61
              - cluster: eng-dev62
              - cluster: eng-dev63
              - cluster: eng-dev64
              - cluster: eng-dev65
              - cluster: eng-dev66
              - cluster: eng-dev67
              - cluster: eng-dev68
              - cluster: eng-dev69
              - cluster: eng-dev70
              - cluster: eng-dev71
              - cluster: eng-dev72
              - cluster: eng-dev73
              - cluster: eng-dev74
              - cluster: eng-dev75
              - cluster: eng-dev76
              - cluster: eng-dev77
              - cluster: eng-dev78
              - cluster: eng-dev79
              - cluster: eng-dev80
              - cluster: eng-dev81
              - cluster: eng-dev82
              - cluster: eng-dev83
              - cluster: eng-dev84
              - cluster: eng-dev85
              - cluster: eng-dev86
              - cluster: eng-dev87
              - cluster: eng-dev88
              - cluster: eng-dev89
              - cluster: eng-dev90
              - cluster: eng-dev91
              - cluster: eng-dev92
              - cluster: eng-dev93
              - cluster: eng-dev94
              - cluster: eng-dev95
              - cluster: eng-dev96
              - cluster: eng-dev97
              - cluster: eng-dev98
              - cluster: eng-dev99
              - cluster: eng-dev100

  template:
    metadata:
      name: '{{ "{{" }}.nameNormalized{{ "}}" }}-{{ "{{" }}.cluster{{ "}}" }}-{{ printf "ccc-%s" .name }}'
    spec:
      project: {{ $config.project }}
      source:
        repoURL: {{ $config.repoURL }}
        targetRevision: {{ $config.targetRevision }}
        path: {{ $config.path }}
        helm:
          values: |
            someValue: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example-%s" .name }}'
            name: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example-%s" .name }}'
            namespace: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example-%s" .name }}'
      destination:
        namespace: '{{ "{{" }}.cluster{{ "}}" }}-{{ printf "example-%s" .name }}'
        server: '{{ "{{" }}.server{{ "}}" }}'
      syncPolicy:
        syncOptions:
        - Replace=true
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
---
{{ end -}}
