apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  labels:
    harness.io/envRef: test
    harness.io/serviceRef: test
  namespace: mirko-namespaced
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook
    server: {{ .Values.spec.destination.server }}
  project: 14a3dc9e
  source:
    path: helm-guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
