apiVersion: v1
data:
  name: {{ .Values.repository.name | b64enc }}
  project: {{ .Values.repository.project | b64enc }}
  type: {{ .Values.repository.type | b64enc }}
  url: {{ .Values.repository.url | b64enc  }}
  username: {{ .Values.repository.username | b64enc }} 
  password: {{ .Values.repository.password | b64enc }} 
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: {{ .Values.repsitory.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
