apiVersion: v1
stringData:
  name: {{ .Values.repository.name | default "" }}
  project: {{ .Values.repository.project | default "" }}
  type: {{ .Values.repository.type | default "git" }}
  url: {{ .Values.repository.url | default "" }}
  username: {{ .Values.repository.username | default "" }}
  password: {{ .Values.repository.password | default "" }}
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: {{ .Values.repository.name | default "repo-unknown" }}
  namespace: {{ .Values.namespace }}
type: Opaque
