apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-appset
  namespace: mirko-account-qa-free-ha
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/mteodor/argocd-example-apps
      revision: HEAD
      directories:
      - path: nginx/helm-appset/templates/*
  template:
    metadata:
      name: '{{.path.basename}}'
      labels:
        harness.io/envRef: Prod
        harness.io/serviceRef: helmappset
    spec:
      project: "5b02f9dc"
      source:
        path: nginx
        repoURL: https://github.com/mteodor/argocd-example-apps
        helm:
          valueFiles:
          - '{{.path.path}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
